### ISSUE TITLE
Project board and issues label

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/glpi-library-ios#1]
Hi, @hectorerb  

Could you prepare project board and the label of the issues.

Two Projects

* Website
* Library

Thanks.

**Comment by hectorerb** [comment]
Labels of the issues https://github.com/flyve-mdm/glpi-library-ios/labels

**Comment by hectorerb** [comment]
Project board https://github.com/flyve-mdm/glpi-library-ios/projects
